config/routes.rb
Rails.application.routes.draw do
  root 'top#main'
  get 'top/main'
  resources :products
  resources :cartitems,only:[:create,:destroy]
  resources :carts
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :cartitems
end

app/models/cartitme.rb
class Cartitme < ActiveRecord::Base
  belongs_to :product
  belongs_to :cart
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :cartitem
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  private
   def current_cart
     if session[cart_id]
       cart = Cart.find(session[:cart_id])
     else
      cart = Cart.create
      session[:cart_id] = cart_id
     end
    cart
   end
   helper_method:current_cart
end

app/controllers/cartitems_controller.rb
class CartitemsController < ApplicationController
 def create
  qty = params[:qty]
  product_id = params[:product_id]
  cartitem = Cartitme.new(qty: qty,product_id: product_id)
  cartitem.save
  redirect_to top_main_path
 end
 def destroy
   cartitem = Cartitme.find(params[:id])
   cartitem.destroy
   redirect_to carts_path
 end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    def index
        @cartitems = Cartitme.all
        @total_price = 0
        @cartitems.each do |cartitem|
          @total_price += cartitem.product.price * cartitem.qty
        end
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end
  def new
    @product = Product.new
  end
  def create
    name = params[:product][:name]
    price = params[:product][:price]
    product = Product.new(name: name,price: price)
    product.save
    redirect_to '/products'
  end
  def destroy
   product = Product.find(params[:id])
   product.destroy
   redirect_to '/products'
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def main
    @products = Product.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cartitems_helper.rb
module CartitemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/carts/index.html.erb
<table border="1" >
<tr>
<th>商品</th>
<th>値段</th>
<th>個数</th>
<th>削除</th>
</tr>
<% @cartitems.each do |cartitem| %>
<tr>
<td><%= cartitem.product.name %></td>
<td><%= cartitem.product.price %>円</td>
<td><%= cartitem.qty %>個</td>
<td><%= link_to '商品の削除', cartitem_path(cartitem.id), method: :delete %></td>
</tr>
<%end%>
</table>
<p>
総額<%= @total_price %>円
</p>
<%= link_to '戻る', "/"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shopping</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/index.html.erb
<%= link_to '新規追加', new_product_path %> 
<% @products.each do |product| %>
<p>
  <%= product.name %>
  <%= product.price %>円
  <%= link_to '商品の削除', "carts_path#{product.id}", method: :delete %>
</p>
<% end %>
<%= link_to '戻る', "/"%>

app/views/products/new.html.erb
<%= form_for @product , url: {action: :create} do |f| %>
<p>
  <%= f.label :name, '商品名' %>
  <%= f.text_field :name %>
</p>
<p>
  <%= f.label :price, '価格' %>
  <%= f.text_field :price %>
</p>
<%= f.submit '登録' %>
<% end %>

app/views/top/main.html.erb
 AMASON.COM
 <%= link_to '商品追加', products_path %> 
 <%= flash[:danger] %>
 <% @products.each do |product| %>
<p>
  <%= product.name %>
  <%= product.price %>円
  <%= form_tag cartitems_path(product_id: product.id), method: :post do %>
  <%= number_field_tag :qty %>個
  <%= submit_tag 'カートに入れる' %>
  <% end %>
</p>
<% end %>
<br>
<%= link_to 'カートの中', carts_path %> 